export const GET_USER = "GET_USER";
export const GET_COURSE = "GET_COURSE";
export const ADD_COURSE = "ADD_COURSE";
export const IS_AUTH = "IS_AUTH";
export const LOG_OUT = "LOG_OUT";
export const ISIGNUP = "SIGN_UP";

export const GETCOURSES = "GETCOURSES";
export const GETCOURSESSUCCESS = "GETCOURSESSUCCESS";
export const GETCOURSESFAILURE = "GETCOURSESFAILURE";

export const GET_CURRENT_COURSE = "GET_CURRENT_COURSE";
export const GET_CURRENT_COURSE_SUCCESS = "GET_CURRENT_COURSE_SUCCESS";
export const GET_CURRENT_COURSE_FAILURE = "GET_CURRENT_COURSE_FAILURE";

export const GETSTUDENTGENERAL = "GETSTUDENTGENERAL";
export const GETSTUDENTGENERALSUCCESS = "GETSTUDENTGENERALSUCCESS";
export const GETSTUDENTGENERALFAILURE = "GETSTUDENTGENERALFAILURE";

export const GETUSER = "GETUSER";
export const GETUSERSUCCESS = "GETUSERSUCCESS";
export const GETUSERFAILURE = "GETUSERFAILURE";


export const STUDENT_INFO = "STUDENT_INFO";
export const STUDENT_ADDRESS_INFO = "STUDENT_ADDRESS_INFO";
export const STUDENT_EDUCATION_INFO = " STUDENT_EDUCATION_INFO";
export const  STUDENT_FILE_INFO="STUDENT_FILE_INFO";
export const PAYEMNET_INITIATE ="PAYEMNET_INITIATE";
export const PAYMENT_VERIFY=" PAYMENT_VERIFY";

export const IS_AUTH_SUCCESS="IS_AUTH_SUCCESS";
export const IS_AUTH_FAILURE="IS_AUTH_FAILURE";

export  const STUDENT_INFO_SUCCESS="STUDENT_INFO_SUCCESS";
export const STUDENT_INFO_FAILURE="STUDENT_INFO_FAILURE";
export const STUDENT_ADDRESS_INFO_SUCCESS="STUDENT_ADDRESS_INFO_SUCCESS";
export const STUDENT_ADDRESS_INFO_FAILURE="STUDENT_ADDRESS_INFO_FAILURE";
export const STUDENT_EDUCATION_INFO_SUCCESS = " STUDENT_EDUCATION_INFO_SUCCESS";
export const STUDENT_EDUCATION_INFO_FAILURE = " STUDENT_EDUCATION_INFO_FAILURE";
export const  STUDENT_FILE_INFO_SUCCESS="STUDENT_FILE_INFO_SUCCESS";
export const  STUDENT_FILE_INFO_FAILURE="STUDENT_FILE_INFO_FAILURE";

export const FORGOT_PASSWORD="FORGOT_PASSWORD";
export const FORGOT_PASSWORD_FAILURE="FORGOT_PASSWORD_FAILURE";
export  const FORGOT_PASSWORD_SUCCESS="FORGOT_PASSWORD_SUCCESS";
export const PAYEMNET_INITIATE_FAILURE="PAYEMNET_INITIATE_FAILURE";
export  const PAYEMNET_INITIATE_SUCCESS="PAYEMNET_INITIATE_SUCCESS";
export const PAYEMNET_VERIFY_FAILURE="PAYEMNET_VERIFY_FAILURE";
export  const PAYEMNET_VERIFY_SUCCESS="PAYEMNET_VERIFY_SUCCESS";

