export const GET_USER = "GET_USER";
export const GET_COURSE = "GET_COURSE";
export const ADD_COURSE = "ADD_COURSE";
export const IS_AUTH = "IS_AUTH";
export const LOG_OUT = "LOG_OUT";
export const ISIGNUP = "SIGN_UP";
export const STUDENT_INFO = "STUDENT_INFO";
export const IS_AUTH_SUCCESS="IS_AUTH_SUCCESS"
export const IS_AUTH_FAILURE="IS_AUTH_FAILURE"
export  const STUDENT_INFO_SUCCESS="STUDENT_INFO_SUCCESS"
export const STUDENT_INFO_FAILURE="STUDENT_INFO_FAILURE"
export const FORGOT_PASSWORD="FORGOT_PASSWORD"
export const FORGOT_PASSWORD_FAILURE="FORGOT_PASSWORD_FAILURE"
export  const FORGOT_PASSWORD_SUCCESS="FORGOT_PASSWORD_SUCCESS"

